// <auto-generated />
using System;
using InventoryApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InventoryApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InventoryApp.Models.AppUser", b =>
            {
                b.Property<string>("Id").HasColumnType("text");
                b.Property<string>("AvatarUrl").HasColumnType("text");
                b.Property<int>("AccessFailedCount").HasColumnType("integer");
                b.Property<string>("ConcurrencyStamp").HasColumnType("text");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<string>("DisplayName").IsRequired().HasColumnType("text");
                b.Property<string>("Email").HasMaxLength(256).HasColumnType("character varying(256)");
                b.Property<bool>("EmailConfirmed").HasColumnType("boolean");
                b.Property<bool>("IsBlocked").HasColumnType("boolean");
                b.Property<bool>("LockoutEnabled").HasColumnType("boolean");
                b.Property<DateTimeOffset?>("LockoutEnd").HasColumnType("timestamp with time zone");
                b.Property<string>("NormalizedEmail").HasMaxLength(256).HasColumnType("character varying(256)");
                b.Property<string>("NormalizedUserName").HasMaxLength(256).HasColumnType("character varying(256)");
                b.Property<string>("PasswordHash").HasColumnType("text");
                b.Property<string>("PhoneNumber").HasColumnType("text");
                b.Property<bool>("PhoneNumberConfirmed").HasColumnType("boolean");
                b.Property<string>("SecurityStamp").HasColumnType("text");
                b.Property<bool>("TwoFactorEnabled").HasColumnType("boolean");
                b.Property<string>("UserName").HasMaxLength(256).HasColumnType("character varying(256)");
                b.HasKey("Id");
                b.HasIndex("NormalizedEmail").HasDatabaseName("EmailIndex");
                b.HasIndex("NormalizedUserName").IsUnique().HasDatabaseName("UserNameIndex");
                b.ToTable("AspNetUsers", (string)null);
            });

            modelBuilder.Entity("InventoryApp.Models.Inventory", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                b.Property<string>("Title").IsRequired().HasColumnType("text");
                b.Property<string>("Description").IsRequired().HasColumnType("text");
                b.Property<string>("Category").HasColumnType("text");
                b.Property<string>("CustomIdFormat").IsRequired().HasColumnType("text");
                b.Property<string>("ImageUrl").HasColumnType("text");
                b.Property<bool>("IsPublic").HasColumnType("boolean");
                b.Property<string>("OwnerId").IsRequired().HasColumnType("text");
                b.Property<string>("Tags").IsRequired().HasColumnType("text");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<DateTime>("UpdatedAt").HasColumnType("timestamp with time zone");
                b.Property<string>("StringField1Name").HasColumnType("text");
                b.Property<string>("StringField2Name").HasColumnType("text");
                b.Property<string>("StringField3Name").HasColumnType("text");
                b.Property<string>("TextField1Name").HasColumnType("text");
                b.Property<string>("TextField2Name").HasColumnType("text");
                b.Property<string>("TextField3Name").HasColumnType("text");
                b.Property<string>("NumberField1Name").HasColumnType("text");
                b.Property<string>("NumberField2Name").HasColumnType("text");
                b.Property<string>("NumberField3Name").HasColumnType("text");
                b.Property<string>("LinkField1Name").HasColumnType("text");
                b.Property<string>("LinkField2Name").HasColumnType("text");
                b.Property<string>("LinkField3Name").HasColumnType("text");
                b.Property<string>("BoolField1Name").HasColumnType("text");
                b.Property<string>("BoolField2Name").HasColumnType("text");
                b.Property<string>("BoolField3Name").HasColumnType("text");
                b.HasKey("Id");
                b.HasIndex("OwnerId");
                b.HasIndex("Title");
                b.ToTable("Inventories");
            });

            modelBuilder.Entity("InventoryApp.Models.Item", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                b.Property<string>("CustomId").IsRequired().HasColumnType("text");
                b.Property<int>("InventoryId").HasColumnType("integer");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<DateTime>("UpdatedAt").HasColumnType("timestamp with time zone");
                b.Property<byte[]>("RowVersion").IsRequired().IsRowVersion().HasColumnType("bytea");
                b.Property<string>("SearchVector").IsRequired().HasColumnType("text");
                b.Property<string>("StringValue1").HasColumnType("text");
                b.Property<string>("StringValue2").HasColumnType("text");
                b.Property<string>("StringValue3").HasColumnType("text");
                b.Property<string>("TextValue1").HasColumnType("text");
                b.Property<string>("TextValue2").HasColumnType("text");
                b.Property<string>("TextValue3").HasColumnType("text");
                b.Property<double?>("NumberValue1").HasColumnType("double precision");
                b.Property<double?>("NumberValue2").HasColumnType("double precision");
                b.Property<double?>("NumberValue3").HasColumnType("double precision");
                b.Property<string>("LinkValue1").HasColumnType("text");
                b.Property<string>("LinkValue2").HasColumnType("text");
                b.Property<string>("LinkValue3").HasColumnType("text");
                b.Property<bool?>("BoolValue1").HasColumnType("boolean");
                b.Property<bool?>("BoolValue2").HasColumnType("boolean");
                b.Property<bool?>("BoolValue3").HasColumnType("boolean");
                b.HasKey("Id");
                b.HasIndex("CustomId");
                b.HasIndex("InventoryId");
                b.HasIndex("SearchVector");
                b.ToTable("Items");
            });

            modelBuilder.Entity("InventoryApp.Models.InventoryAccess", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                b.Property<int>("InventoryId").HasColumnType("integer");
                b.Property<string>("UserId").IsRequired().HasColumnType("text");
                b.HasKey("Id");
                b.HasIndex("UserId");
                b.HasIndex("InventoryId", "UserId").IsUnique();
                b.ToTable("InventoryAccesses");
            });

            modelBuilder.Entity("InventoryApp.Models.Comment", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                b.Property<string>("AuthorId").IsRequired().HasColumnType("text");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<int?>("InventoryId").HasColumnType("integer");
                b.Property<int?>("ItemId").HasColumnType("integer");
                b.Property<string>("Text").IsRequired().HasColumnType("text");
                b.HasKey("Id");
                b.HasIndex("AuthorId");
                b.HasIndex("InventoryId");
                b.HasIndex("ItemId");
                b.ToTable("Comments");
            });

            modelBuilder.Entity("InventoryApp.Models.Like", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                b.Property<int?>("ItemId").HasColumnType("integer");
                b.Property<string>("UserId").IsRequired().HasColumnType("text");
                b.HasKey("Id");
                b.HasIndex("ItemId");
                b.HasIndex("UserId", "ItemId").IsUnique().HasFilter("\"ItemId\" IS NOT NULL");
                b.ToTable("Likes");
            });
#pragma warning restore 612, 618
        }
    }
}
